" enable syntax highlighting
syntax on

set tabstop=4 softtabstop=4 shiftwidth=4

" expand tabs into spaces
set expandtab

" indent when moving to the next line while writing code
set autoindent

" clipboard
set clipboard

